### ISSUE TITLE
unknown config object 'save_variables' when including filaments into the config

### ISSUE THREAD

**Issue by Nathan22211** [garethky/filaments-klipper-extra#2]
I largely just have `[filaments]` in my printer config for this and this is occurring looking at the klippy log I found this

```
Config error
Traceback (most recent call last):
  File "/home/klipper/klipper/klippy/klippy.py", line 175, in _connect
    self._read_config()
  File "/home/klipper/klipper/klippy/klippy.py", line 141, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/klipper/klipper/klippy/klippy.py", line 130, in load_object
    self.objects[section] = init_func(config.getsection(section))
  File "/home/klipper/klipper/klippy/extras/filaments.py", line 436, in load_config
    return FilamentPresets(config)
  File "/home/klipper/klipper/klippy/extras/filaments.py", line 16, in __init__
    self.save_vars = self.printer.lookup_object('save_variables')
  File "/home/klipper/klipper/klippy/klippy.py", line 97, in lookup_object
    raise self.config_error("Unknown config object '%s'" % (name,))
configparser.Error: Unknown config object 'save_variables'
```

**Comment by garethky** [comment]
Yes, that's right, you need a `[save_variables]` config section. [See documentation here](https://www.klipper3d.org/Config_Reference.html#save_variables).

I don't see this mentioned in the readme so the docs need an update.

**Comment by Nathan22211** [comment]
just going to mention this now, it seems you made changes to the naming of the extra's config and variables. What you have in the docs for custom parameters now gives this error when it runs across it `!! Error on 'set_pressure_advance advance={printer.extruder.filament.pa}': unable to parse {printer.extruder.filament.pa}`
